spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasktracker
    username: task_user
    password: secret123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

